//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.24 at 10:07:51 AM GMT+08:00 
//

package com.chenjh.common.nvd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>Java class for refType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="refType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="source" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="url" use="required" type="{http://nvd.nist.gov/feeds/cve/1.2}urlType" />
 *       &lt;attribute name="sig" type="{http://nvd.nist.gov/feeds/cve/1.2}trueOnlyAttribute" />
 *       &lt;attribute name="adv" type="{http://nvd.nist.gov/feeds/cve/1.2}trueOnlyAttribute" />
 *       &lt;attribute name="patch" type="{http://nvd.nist.gov/feeds/cve/1.2}trueOnlyAttribute" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "refType", propOrder = {"value" })
public class RefType
{
    
    @XmlValue
    private String value;
    
    @XmlAttribute(name = "source", required = true)
    private String source;
    
    @XmlAttribute(name = "url", required = true)
    private String url;
    
    @XmlAttribute(name = "sig")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    private String sig;
    
    @XmlAttribute(name = "adv")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    private String adv;
    
    @XmlAttribute(name = "patch")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    private String patch;
    
    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue()
    {
        return value;
    }
    
    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value)
    {
        this.value = value;
    }
    
    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource()
    {
        return source;
    }
    
    /**
     * Sets the value of the source property.
     * 
     * @param souceVal
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String souceVal)
    {
        this.source = souceVal;
    }
    
    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl()
    {
        return url;
    }
    
    /**
     * Sets the value of the url property.
     * 
     * @param urlVal
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String urlVal)
    {
        this.url = urlVal;
    }
    
    /**
     * Gets the value of the sig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSig()
    {
        return sig;
    }
    
    /**
     * Sets the value of the sig property.
     * 
     * @param sigVal
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSig(String sigVal)
    {
        this.sig = sigVal;
    }
    
    /**
     * Gets the value of the adv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdv()
    {
        return adv;
    }
    
    /**
     * Sets the value of the adv property.
     * 
     * @param advVal
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdv(String advVal)
    {
        this.adv = advVal;
    }
    
    /**
     * Gets the value of the patch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatch()
    {
        return patch;
    }
    
    /**
     * Sets the value of the patch property.
     * 
     * @param patchVal
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatch(String patchVal)
    {
        this.patch = patchVal;
    }
    
}
