//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.24 at 10:07:51 AM GMT+08:00 
//

package com.chenjh.common.nvd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for solsSourceType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="solsSourceType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="nvd"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "solsSourceType")
@XmlEnum
public enum SolsSourceType
{
    /**
     * value
     */
    @XmlEnumValue("nvd")
    NVD("nvd");
    private final String value;
    
    SolsSourceType(String v)
    {
        value = v;
    }
    
    /**
     * value
     * @return value
     
     * @date 2016年9月24日
     */
    public String value()
    {
        return value;
    }
    
    /**
     * SolsSourceType
     * @param v value
     * @return SolsSourceType
     
     * @date 2016年9月24日
     */
    public static SolsSourceType fromValue(String v)
    {
        for (SolsSourceType c : SolsSourceType.values())
        {
            if (c.value.equals(v))
            {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
    
}
