package com.chenjh.domain.nvd;

import java.math.BigDecimal;
import java.util.Date;

/**
 * 
 * <p>Title:  </p>
 * <p>Description:  </p>
 * <pre>  </pre>
 * <p>Copyright: Copyright (c) 2014</p>
 * <p>Company: </p>
 
 * @version V1.0 2016年9月21日
 * @since
 */
public class NvdVulInfoBean
{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ND_VUL_INFO.CVE_ID
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    private String cveId;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ND_VUL_INFO.VUL_TITLE
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    private String vulTitle;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ND_VUL_INFO.VUL_DESCRIPTION
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    private String vulDescription;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ND_VUL_INFO.CVSS_VER
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    private String cvssVer;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ND_VUL_INFO.CVSS_SCORE
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    private BigDecimal cvssScore;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ND_VUL_INFO.CVSS_VECTOR
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    private String cvssVector;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ND_VUL_INFO.PUBLISHED_DATE
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    private Date publishedDate;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ND_VUL_INFO.VUL_MOD_DATE
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    private Date vulModDate;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ND_VUL_INFO.PROC_STATUS
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    private Integer procStatus;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ND_VUL_INFO.CREATED_TIME
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    private Date createdTime;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ND_VUL_INFO.MODIFIED_TIME
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    private Date modifiedTime;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ND_VUL_INFO.NOTE
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    private String note;
    
    /**
     * cvssStatus
     */
    private Integer cvssStatus;
    
    /**
     * 状态，有效，无效
     */
    private Integer status;
    
    /**
     * 漏洞对应cveEntity的hashCode
     */
    private Integer flag;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ND_VUL_INFO.CVE_ID
     *
     * @return the value of T_ND_VUL_INFO.CVE_ID
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    public String getCveId()
    {
        return cveId;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ND_VUL_INFO.CVE_ID
     *
     * @param cveId the value for T_ND_VUL_INFO.CVE_ID
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    public void setCveId(String cveId)
    {
        this.cveId = cveId == null ? null : cveId.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ND_VUL_INFO.VUL_TITLE
     *
     * @return the value of T_ND_VUL_INFO.VUL_TITLE
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    public String getVulTitle()
    {
        return vulTitle;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ND_VUL_INFO.VUL_TITLE
     *
     * @param vulTitle the value for T_ND_VUL_INFO.VUL_TITLE
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    public void setVulTitle(String vulTitle)
    {
        this.vulTitle = vulTitle == null ? null : vulTitle.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ND_VUL_INFO.VUL_DESCRIPTION
     *
     * @return the value of T_ND_VUL_INFO.VUL_DESCRIPTION
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    public String getVulDescription()
    {
        return vulDescription;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ND_VUL_INFO.VUL_DESCRIPTION
     *
     * @param vulDescription the value for T_ND_VUL_INFO.VUL_DESCRIPTION
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    public void setVulDescription(String vulDescription)
    {
        this.vulDescription = vulDescription == null ? null : vulDescription.trim();
    }
    
    public String getCvssVer()
    {
        return cvssVer;
    }
    
    public void setCvssVer(String cvssVer)
    {
        this.cvssVer = cvssVer;
    }
    
    public BigDecimal getCvssScore()
    {
        return cvssScore;
    }
    
    public void setCvssScore(BigDecimal cvssScore)
    {
        this.cvssScore = cvssScore;
    }
    
    public String getCvssVector()
    {
        return cvssVector;
    }
    
    public void setCvssVector(String cvssVector)
    {
        this.cvssVector = cvssVector;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ND_VUL_INFO.PUBLISHED_DATE
     *
     * @return the value of T_ND_VUL_INFO.PUBLISHED_DATE
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    public Date getPublishedDate()
    {
        return publishedDate;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ND_VUL_INFO.PUBLISHED_DATE
     *
     * @param publishedDate the value for T_ND_VUL_INFO.PUBLISHED_DATE
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    public void setPublishedDate(Date publishedDate)
    {
        this.publishedDate = publishedDate;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ND_VUL_INFO.VUL_MOD_DATE
     *
     * @return the value of T_ND_VUL_INFO.VUL_MOD_DATE
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    public Date getVulModDate()
    {
        return vulModDate;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ND_VUL_INFO.VUL_MOD_DATE
     *
     * @param vulModDate the value for T_ND_VUL_INFO.VUL_MOD_DATE
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    public void setVulModDate(Date vulModDate)
    {
        this.vulModDate = vulModDate;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ND_VUL_INFO.PROC_STATUS
     *
     * @return the value of T_ND_VUL_INFO.PROC_STATUS
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    public Integer getProcStatus()
    {
        return procStatus;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ND_VUL_INFO.PROC_STATUS
     *
     * @param procStatus the value for T_ND_VUL_INFO.PROC_STATUS
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    public void setProcStatus(Integer procStatus)
    {
        this.procStatus = procStatus;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ND_VUL_INFO.CREATED_TIME
     *
     * @return the value of T_ND_VUL_INFO.CREATED_TIME
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    public Date getCreatedTime()
    {
        return createdTime;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ND_VUL_INFO.CREATED_TIME
     *
     * @param createdTime the value for T_ND_VUL_INFO.CREATED_TIME
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    public void setCreatedTime(Date createdTime)
    {
        this.createdTime = createdTime;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ND_VUL_INFO.MODIFIED_TIME
     *
     * @return the value of T_ND_VUL_INFO.MODIFIED_TIME
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    public Date getModifiedTime()
    {
        return modifiedTime;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ND_VUL_INFO.MODIFIED_TIME
     *
     * @param modifiedTime the value for T_ND_VUL_INFO.MODIFIED_TIME
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    public void setModifiedTime(Date modifiedTime)
    {
        this.modifiedTime = modifiedTime;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ND_VUL_INFO.NOTE
     *
     * @return the value of T_ND_VUL_INFO.NOTE
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    public String getNote()
    {
        return note;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ND_VUL_INFO.NOTE
     *
     * @param note the value for T_ND_VUL_INFO.NOTE
     *
     * @mbggenerated Fri Sep 09 10:51:12 GMT+08:00 2016
     */
    public void setNote(String note)
    {
        this.note = note == null ? null : note.trim();
    }
    
    public Integer getCvssStatus()
    {
        return cvssStatus;
    }
    
    public void setCvssStatus(Integer cvssStatus)
    {
        this.cvssStatus = cvssStatus;
    }
    
    public Integer getStatus()
    {
        return status;
    }
    
    public void setStatus(Integer status)
    {
        this.status = status;
    }
    
    public Integer getFlag()
    {
        return flag;
    }

    public void setFlag(Integer flag)
    {
        this.flag = flag;
    }

    /**
     * 重写toString
     * @return string
     */
    @Override
    public String toString()
    {
        StringBuilder builder = new StringBuilder();
        builder.append("NvdVulInfoBean [cveId=");
        builder.append(cveId);
        builder.append(", vulTitle=");
        builder.append(vulTitle);
        builder.append(", vulDescription=");
        builder.append(vulDescription);
        builder.append(", cvssVer=");
        builder.append(cvssVer);
        builder.append(", cvssScore=");
        builder.append(cvssScore);
        builder.append(", cvssVector=");
        builder.append(cvssVector);
        builder.append(", publishedDate=");
        builder.append(publishedDate);
        builder.append(", vulModDate=");
        builder.append(vulModDate);
        builder.append(", procStatus=");
        builder.append(procStatus);
        builder.append(", createdTime=");
        builder.append(createdTime);
        builder.append(", modifiedTime=");
        builder.append(modifiedTime);
        builder.append(", note=");
        builder.append(note);
        builder.append("cvssStatus=");
        builder.append(cvssStatus);
        builder.append("status=");
        builder.append(status);
        builder.append("flag=");
        builder.append(flag);
        builder.append(']');
        return builder.toString();
    }
}
